
# ~BrieFlow analysis configuration file~

# All paths are resolved relative to the directory the workflow is run from.

# Parameters:
all:
  root_fp: analysis_root
phenotype:
  align: false
  cell_cellprob_threshold: 1
  cell_diameter: 300
  cell_flow_threshold: 0.4
  channel_names:
  - DAPI
  - ConA
  - Stat6
  - Mitotracker
  - NHS_ester
  - Tubulin
  - WGA
  - cMYC
  - CDPK1
  cp_method: cp_multichannel
  custom_align: true
  cyto_index: 4
  cyto_model: cpsam
  dapi_index: 0
  foci_channel: null
  gpu: false
  helper_index: 5
  min_distance_between_maxima: 25
  mode: null
  nuclei_cellprob_threshold: 0
  nuclei_detection: false
  nuclei_diameter: 100
  nuclei_flow_threshold: 0.4
  offsets_dict:
    5:
    - -5
    - 15
    7:
    - -15
    - 35
    8:
    - -15
    - 35
    9:
    - -15
    - 35
    10:
    - -15
    - 35
  reconcile: contained_in_cells
  remove_channel_custom:
  - 4
  - 6
  segment_cells: true
  segmentation_method: cellpose
  vacuole_channel_index: 8
  vacuole_detection: true
  vacuole_max_size: 200
  vacuole_min_size: 10
preprocess:
  phenotype_best_focus_channel:
  - 3
  - 1
  - 2
  phenotype_channel_order: null
  phenotype_channel_order_flip: false
  phenotype_combo_fp: config/phenotype_combo.tsv
  phenotype_round_order:
  - 1
  - 2
  - 3
  phenotype_samples_fp: config/phenotype_samples.tsv
  phenotype_z_handling: best_focus
  sample_fraction: 0.25
  sbs_best_focus_channel:
  - 0
  sbs_channel_order: null
  sbs_channel_order_flip: true
  sbs_combo_fp: config/sbs_combo.tsv
  sbs_samples_fp: config/sbs_samples.tsv
  sbs_z_handling: no_z
sbs:
  alignment_method: DAPI
  channel_names:
  - DAPI
  - G
  - T
  - A
  - C
  upsample_factor: 2
  skip_cycles_indices:
  - 4
  manual_background_cycle_index: null
  extra_channel_indices:
  - 0
  max_filter_width: 3
  spot_detection_method: standard
  dapi_cycle: 1
  cyto_cycle: 1
  cyto_cycle_index: 0
  dapi_index: 0
  cyto_index: 1
  segmentation_method: watershed
  gpu: false
  segment_cells: false
  df_barcode_library_fp: config/barcode_library.tsv
  sequencing_order: map_recomb
  threshold_peaks: 150
  call_reads_method: percentile
  bases:
  - G
  - T
  - A
  - C
  q_min: 0
  recomb_start: 7
  recomb_end: 8
  map_start: 1
  map_end: 6
  map_col: prefix_map
  recomb_col: prefix_recomb
  recomb_filter_col: Q_recomb
  error_correct: true
  recomb_q_thresh: 0.5
  barcode_info_cols:
  - gene_symbol
  max_distance: 2
  sort_calls: peak
  mode: null
  peak_width: 15
  threshold_dapi: 470
  nucleus_area_min: 70
  nucleus_area_max: 800
  threshold_cell: 1300
  log_transform: false
merge:
  det_range:
  - 0.015
  - 0.017
  initial_sites:
  - - 2795
    - 190
  - - 5809
    - 374
  - - 2996
    - 194
  merge_combo_fp: config/merge_combo.tsv
  ph_metadata_channel: null
  sbs_metadata_channel: null
  sbs_metadata_cycle: 1
  score: 0.1
  threshold: 10